apiVersion: v1
kind: Pod
metadata:
  name: kc-themes-explorer
  namespace: keycloak
spec:
  containers:
    - name: pvc-explorer
      image: ubuntu:20.04
      stdin: true
      tty: true
      workingDir: /opt/bitnami/keycloak/themes
      volumeMounts:
      - mountPath: "/opt/bitnami/keycloak/themes"
        name: data
      - mountPath: "/nfs"
        name: nfs
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: keycloak-theme
    - name: nfs
      nfs:
        path: /taiga/ncsa/radiant/bbfa/
        server: taiga-nfs.ncsa.illinois.edu
